import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Jost } from "next/font/google";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const jost = Jost({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-jost",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${jost.variable} font-sans`}>
            <body>
                <div className="flex flex-col min-h-screen">
                    <Navbar />
                    <main className="flex-1">{children}</main>
                </div>
            </body>
        </html>
    );
}
